# Generated by Django 3.2 on 2023-06-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200925_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='')),
                ('description', models.TextField(default='comming soon', max_length=50)),
                ('trailer_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NextMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='')),
                ('description', models.TextField(default='comming soon', max_length=50)),
                ('trailer_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
