# Generated by Django 3.2 on 2023-06-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movies_nextmovies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='about',
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(default='Action', max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
