# Generated by Django 3.2 on 2023-06-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20230619_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
