# Generated by Django 3.2 on 2023-06-21 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
